### ISSUE TITLE
Quest mods

### ISSUE THREAD

**Issue by The-Techy** [zakmasood/BricksVRModding#2]
Would be great if the mods worked on quest, there are ways to do it (BMBF), and I think melonloader works on it

**Comment by ATXLtheAxolotl** [comment]
BMBF does it a separate way using C++, I was looking into this however I never managed to successfully generate any headers or codegens to interact with the game. Melonloader's android support has slowed down and it was made a separate project called Lemon (I believe). I tried using that however it was very difficult and I never got it to work.

**Comment by zakmasood** [comment]
Yep ATXL is right, melon loader did develop android support but I also never got it to work.
What you could do however is use sidequest and run bricksVR on steam onto your quest. That way you only have to mod the steam version.

**Comment by zakmasood** [comment]
Late update:
The melonloader dev team did fix support for lemonloader and I think it should be better and easier to use, although I have not tried using it.
